{% set name = "pyepics" %}
{% set version = "3.3.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  git_rev: {{ version }}
  git_url: https://github.com/pyepics/pyepics.git

build:
  number: 0
  script: python setup.py install --single-version-externally-managed --record=record.txt
  skip: True  # [win]

requirements:
  build:
      - python
      - setuptools
  run:
      - python
      - numpy
      - pyparsing

test:
  imports:
    - epics
    - epics.autosave
    - epics.compat
    - epics.devices

about:
  home: http://pyepics.github.io/pyepics/
  license: Epics Open
  summary: Python interface to Epics Channel Access
  # https://github.com/pyepics/pyepics/pull/108
  license_file: '{{ environ["RECIPE_DIR"] }}/LICENSE'
  dev_url: https://github.com/pyepics/pyepics
  doc_url: http://pyepics.github.io/pyepics

extra:
  recipe-maintainers:
    - CJ-Wright
    - jrmlhermitte
    - stuartcampbell
    - mrakitin
